from .aicoco_data_model import (
    AiAnnotation,
    AiCategory,
    AiCOCOImageFormat,
    AiCOCOTabularFormat,
    AiCOCOHybridFormat,
    AiImage,
    AiMeta,
    AiObject,
    AiRecord,
    AiRegression,
    AiRegressionItem,
    AiTable,
    AiTableMeta,
)
