from .aicoco_model import (
    AiAnnotation,
    AiCategory,
    AiCOCOFormat,
    AiImage,
    AiMeta,
    AiObject,
    AiRegression,
    AiRegressionItem,
)
from .flavor_infer_model import (
    DetModelOut,
    InferCategory,
    InferClassificationOutput,
    InferDetectionOutput,
    InferInput,
    InferInputImage,
    InferOutput,
    InferRegression,
    InferRegressionOutput,
    InferSegmentationOutput,
    InputBody,
    ModelOut,
    NpArray,
)
